core:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
          - 'README.md'

ai-rules:
  - changed-files:
      - any-glob-to-any-file:
          - '.kilocode/**'
