"area:core":
  - changed-files:
      - any-glob-to-any-file: "src/**"

"area:tests":
  - changed-files:
      - any-glob-to-any-file: "tests/**"

"area:docs":
  - changed-files:
      - any-glob-to-any-file: "docs/**"
