core:
  - changed-files:
      - any-glob-to-any-file:
          - 'src/**'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - 'tests/**'

docs:
  - changed-files:
      - any-glob-to-any-file:
          - 'docs/**'
