services:
  g2nc:
    # Build local dev image from Dockerfile. Alternatively, replace with a released image (e.g., ghcr.io/yourorg/g2nc:latest)
    build: .
    image: g2nc:dev
    container_name: g2nc
    restart: "no"
    environment:
      # Required: Nextcloud app password (prefer using an .env file to set this securely)
      - NEXTCLOUD_APP_PASSWORD=${NEXTCLOUD_APP_PASSWORD}
      # One of the following must be provided to authenticate to Google:
      # Inline JSON credentials (paste as a single-line JSON string) OR a path to a credentials file mounted inside the container.
      # - GOOGLE_CREDENTIALS_JSON=${GOOGLE_CREDENTIALS_JSON}
      # - GOOGLE_CREDENTIALS_FILE=/data/google_credentials.json
      # Optional timezone for logs and time computations inside the container
      - TZ=${TZ:-UTC}
    command: >
      g2nc sync
      --config /data/config.yaml
    # Mount a host directory for persistent state and configuration.
    # Required files under ./data on the host:
    # - config.yaml                (app configuration)
    # - google_credentials.json    (OAuth client credentials if using GOOGLE_CREDENTIALS_FILE)
    # Will be generated by the app on first run:
    # - google_token.json          (user token; do not commit)
    # - state.sqlite               (sync state DB; do not commit)
    volumes:
      - ./data:/data:rw
    # For cron-style operation, consider using restart: unless-stopped and an external scheduler (host cron/k8s job) to run the container.
    # Alternatively, run in one-shot mode as above and let the orchestrator exit with appropriate code.

# Usage:
# 1) Prepare ./data/config.yaml (see docs/config.md) and ./data/google_credentials.json (or set GOOGLE_CREDENTIALS_JSON).
# 2) Create an .env file in this directory setting:
#      NEXTCLOUD_APP_PASSWORD=your-app-password
#      TZ=Europe/Berlin
#    Optionally:
#      GOOGLE_CREDENTIALS_JSON='{"installed":{...}}'
# 3) Run:
#      docker compose build
#      docker compose run --rm g2nc
#    Subsequent runs can use:
#      docker compose run --rm g2nc